# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
CXX=/usr/lib64/ccache/clang++
MM=/usr/lib64/ccache/clang
CC=/usr/lib64/ccache/clang
MXX=/usr/lib64/ccache/clang++
MRC=/usr/bin/llvm-rc
AS=/usr/lib64/ccache/clang

AR=/usr/bin/llvm-ar
SH=/usr/lib64/ccache/clang++
LD=/usr/lib64/ccache/clang++

celine_bin_LD=/usr/lib64/ccache/clang++
celine_bin_CXX=/usr/lib64/ccache/clang++
celine_bin_CXX=/usr/lib64/ccache/clang++
celine_bin_CXX=/usr/lib64/ccache/clang++
celine_tests_LD=/usr/lib64/ccache/clang++
celine_tests_CXX=/usr/lib64/ccache/clang++
celine_tests_CXX=/usr/lib64/ccache/clang++
celine_tests_CXX=/usr/lib64/ccache/clang++
celine_lib_AR=/usr/bin/llvm-ar
celine_lib_CXX=/usr/lib64/ccache/clang++
celine_lib_CXX=/usr/lib64/ccache/clang++

celine_bin_CXXFLAGS=
celine_bin_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG
celine_bin_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG
celine_bin_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -s -lceline_lib -stdlib=libc++
celine_tests_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -isystem /home/gaybe/.xmake/packages/d/doctest/2.5.3/9a03845fdf324a1fa2b4fe54c46d8b69/include -isystem /home/gaybe/.xmake/packages/d/doctest/2.5.3/9a03845fdf324a1fa2b4fe54c46d8b69/include/doctest -stdlib=libc++ -DNDEBUG
celine_tests_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -isystem /home/gaybe/.xmake/packages/d/doctest/2.5.3/9a03845fdf324a1fa2b4fe54c46d8b69/include -isystem /home/gaybe/.xmake/packages/d/doctest/2.5.3/9a03845fdf324a1fa2b4fe54c46d8b69/include/doctest -stdlib=libc++ -DNDEBUG
celine_tests_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -isystem /home/gaybe/.xmake/packages/d/doctest/2.5.3/9a03845fdf324a1fa2b4fe54c46d8b69/include -isystem /home/gaybe/.xmake/packages/d/doctest/2.5.3/9a03845fdf324a1fa2b4fe54c46d8b69/include/doctest -stdlib=libc++ -DNDEBUG
celine_tests_LDFLAGS=-m64 -Lbuild/linux/x86_64/release -s -lceline_lib -stdlib=libc++
celine_lib_CXXFLAGS=
celine_lib_CXXFLAGS=-Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG
celine_lib_ARFLAGS=cr

default:  celine_bin celine_lib

all:  celine_bin celine_tests celine_lib

.PHONY: default all  celine_bin celine_tests celine_lib

precmds_celine_bin:
	@mkdir -p build/.objs/celine_bin/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.module.bmi.release celine:LinearApp
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -x c++-module --precompile -o build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_bin/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.module.bmi.release celine
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -x c++-module --precompile -o build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c/celine.pcm src/celine/celine.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.module.bmi.release celine:LinearApp
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -x c++-module --precompile -o build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.module.bmi.release celine
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -x c++-module --precompile -o build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c/celine.pcm src/celine/celine.cppm
	@mkdir -p build/.objs/celine_bin/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.release src/celine/LinearApp.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -o build/.objs/celine_bin/linux/x86_64/release/src/celine/LinearApp.cppm.o src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_bin/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.release src/celine/celine.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_bin/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -o build/.objs/celine_bin/linux/x86_64/release/src/celine/celine.cppm.o src/celine/celine.cppm
	@mkdir -p build/.objs/celine_bin/linux/x86_64/release/src
	@rm -rf build/.objs/celine_bin/linux/x86_64/release/src/main.cpp.o
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.release src/celine/LinearApp.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -o build/.objs/celine_lib/linux/x86_64/release/src/celine/LinearApp.cppm.o src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.release src/celine/celine.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -o build/.objs/celine_lib/linux/x86_64/release/src/celine/celine.cppm.o src/celine/celine.cppm

celine_bin: build/linux/x86_64/release/celine_bin
build/linux/x86_64/release/celine_bin: precmds_celine_bin build/linux/x86_64/release/libceline_lib.a build/.objs/celine_bin/linux/x86_64/release/src/main.cpp.o
	@echo linking.release celine_bin
	@mkdir -p build/linux/x86_64/release
	$(VV)$(celine_bin_LD) -o build/linux/x86_64/release/celine_bin build/.objs/celine_bin/linux/x86_64/release/src/main.cpp.o $(celine_bin_LDFLAGS)

build/.objs/celine_bin/linux/x86_64/release/src/main.cpp.o: precmds_celine_bin src/main.cpp
	@echo ccache compiling.release src/main.cpp
	@mkdir -p build/.objs/celine_bin/linux/x86_64/release/src
	$(VV)$(celine_bin_CXX) -c $(celine_bin_CXXFLAGS) -o build/.objs/celine_bin/linux/x86_64/release/src/main.cpp.o src/main.cpp

precmds_celine_tests:
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.module.bmi.release celine:LinearApp
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -x c++-module --precompile -o build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.module.bmi.release celine
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -x c++-module --precompile -o build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c/celine.pcm src/celine/celine.cppm
	@mkdir -p build/.objs/celine_tests/linux/x86_64/release/src/tests
	@rm -rf build/.objs/celine_tests/linux/x86_64/release/src/tests/test_rank.cpp.o
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.release src/celine/LinearApp.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -o build/.objs/celine_lib/linux/x86_64/release/src/celine/LinearApp.cppm.o src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.release src/celine/celine.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -o build/.objs/celine_lib/linux/x86_64/release/src/celine/celine.cppm.o src/celine/celine.cppm

celine_tests: build/linux/x86_64/release/celine_tests
build/linux/x86_64/release/celine_tests: precmds_celine_tests build/linux/x86_64/release/libceline_lib.a build/.objs/celine_tests/linux/x86_64/release/src/tests/test_rank.cpp.o
	@echo linking.release celine_tests
	@mkdir -p build/linux/x86_64/release
	$(VV)$(celine_tests_LD) -o build/linux/x86_64/release/celine_tests build/.objs/celine_tests/linux/x86_64/release/src/tests/test_rank.cpp.o $(celine_tests_LDFLAGS)

build/.objs/celine_tests/linux/x86_64/release/src/tests/test_rank.cpp.o: precmds_celine_tests src/tests/test_rank.cpp
	@echo ccache compiling.release src/tests/test_rank.cpp
	@mkdir -p build/.objs/celine_tests/linux/x86_64/release/src/tests
	$(VV)$(celine_tests_CXX) -c $(celine_tests_CXXFLAGS) -o build/.objs/celine_tests/linux/x86_64/release/src/tests/test_rank.cpp.o src/tests/test_rank.cpp

precmds_celine_lib:
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.module.bmi.release celine:LinearApp
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -x c++-module --precompile -o build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.module.bmi.release celine
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -x c++-module --precompile -o build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c/celine.pcm src/celine/celine.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3
	@echo compiling.release src/celine/LinearApp.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -o build/.objs/celine_lib/linux/x86_64/release/src/celine/LinearApp.cppm.o src/celine/LinearApp.cppm
	@mkdir -p build/.objs/celine_lib/linux/x86_64/release/src/celine
	@mkdir -p build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/interfaces/46a3fa482010d15c
	@echo compiling.release src/celine/celine.cppm
	$(VV)/usr/lib64/ccache/clang++ -c -Qunused-arguments -m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++23 -stdlib=libc++ -DNDEBUG -fmodule-file=celine:LinearApp=build/.gens/celine_lib/linux/x86_64/release/rules/bmi/cache/implementation/b64015b399e091b3/celine_PARTITION_LinearApp.pcm -o build/.objs/celine_lib/linux/x86_64/release/src/celine/celine.cppm.o src/celine/celine.cppm

celine_lib: build/linux/x86_64/release/libceline_lib.a
build/linux/x86_64/release/libceline_lib.a: precmds_celine_lib
	@echo linking.release libceline_lib.a
	@mkdir -p build/linux/x86_64/release
	$(VV)$(celine_lib_AR) $(celine_lib_ARFLAGS) build/linux/x86_64/release/libceline_lib.a

clean:  clean_celine_bin clean_celine_tests clean_celine_lib

clean_celine_bin:  clean_celine_lib
	@rm -rf build/linux/x86_64/release/celine_bin
	@rm -rf build/linux/x86_64/release/celine_bin.sym
	@rm -rf build/.objs/celine_bin/linux/x86_64/release/src/main.cpp.o

clean_celine_tests:  clean_celine_lib
	@rm -rf build/linux/x86_64/release/celine_tests
	@rm -rf build/linux/x86_64/release/celine_tests.sym
	@rm -rf build/.objs/celine_tests/linux/x86_64/release/src/tests/test_rank.cpp.o

clean_celine_lib: 
	@rm -rf build/linux/x86_64/release/libceline_lib.a
	@rm -rf build/linux/x86_64/release/celine_lib.sym

