# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gaybe/Documents/dev/cpp/celine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gaybe/Documents/dev/cpp/celine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gaybe/Documents/dev/cpp/celine/CMakeFiles /home/gaybe/Documents/dev/cpp/celine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gaybe/Documents/dev/cpp/celine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named celine_bin

# Build rule for target.
celine_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 celine_bin
.PHONY : celine_bin

# fast build rule for target.
celine_bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_bin.dir/build.make CMakeFiles/celine_bin.dir/build
.PHONY : celine_bin/fast

#=============================================================================
# Target rules for targets named celine_lib

# Build rule for target.
celine_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 celine_lib
.PHONY : celine_lib

# fast build rule for target.
celine_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib.dir/build.make CMakeFiles/celine_lib.dir/build
.PHONY : celine_lib/fast

#=============================================================================
# Target rules for targets named celine_tests

# Build rule for target.
celine_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 celine_tests
.PHONY : celine_tests

# fast build rule for target.
celine_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_tests.dir/build.make CMakeFiles/celine_tests.dir/build
.PHONY : celine_tests/fast

#=============================================================================
# Target rules for targets named celine_lib@synth_80f53022599d

# Build rule for target.
celine_lib@synth_80f53022599d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 celine_lib@synth_80f53022599d
.PHONY : celine_lib@synth_80f53022599d

# fast build rule for target.
celine_lib@synth_80f53022599d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib@synth_80f53022599d.dir/build.make CMakeFiles/celine_lib@synth_80f53022599d.dir/build
.PHONY : celine_lib@synth_80f53022599d/fast

src/celine/LinearApp.o: src/celine/LinearApp.cppm.o
.PHONY : src/celine/LinearApp.o

# target to build an object file
src/celine/LinearApp.cppm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib.dir/build.make CMakeFiles/celine_lib.dir/src/celine/LinearApp.cppm.o
.PHONY : src/celine/LinearApp.cppm.o

src/celine/LinearApp.i: src/celine/LinearApp.cppm.i
.PHONY : src/celine/LinearApp.i

# target to preprocess a source file
src/celine/LinearApp.cppm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib.dir/build.make CMakeFiles/celine_lib.dir/src/celine/LinearApp.cppm.i
.PHONY : src/celine/LinearApp.cppm.i

src/celine/LinearApp.s: src/celine/LinearApp.cppm.s
.PHONY : src/celine/LinearApp.s

# target to generate assembly for a file
src/celine/LinearApp.cppm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib.dir/build.make CMakeFiles/celine_lib.dir/src/celine/LinearApp.cppm.s
.PHONY : src/celine/LinearApp.cppm.s

src/celine/celine.o: src/celine/celine.cppm.o
.PHONY : src/celine/celine.o

# target to build an object file
src/celine/celine.cppm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib.dir/build.make CMakeFiles/celine_lib.dir/src/celine/celine.cppm.o
.PHONY : src/celine/celine.cppm.o

src/celine/celine.i: src/celine/celine.cppm.i
.PHONY : src/celine/celine.i

# target to preprocess a source file
src/celine/celine.cppm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib.dir/build.make CMakeFiles/celine_lib.dir/src/celine/celine.cppm.i
.PHONY : src/celine/celine.cppm.i

src/celine/celine.s: src/celine/celine.cppm.s
.PHONY : src/celine/celine.s

# target to generate assembly for a file
src/celine/celine.cppm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_lib.dir/build.make CMakeFiles/celine_lib.dir/src/celine/celine.cppm.s
.PHONY : src/celine/celine.cppm.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_bin.dir/build.make CMakeFiles/celine_bin.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_bin.dir/build.make CMakeFiles/celine_bin.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_bin.dir/build.make CMakeFiles/celine_bin.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tests/test_rank.o: src/tests/test_rank.cpp.o
.PHONY : src/tests/test_rank.o

# target to build an object file
src/tests/test_rank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_tests.dir/build.make CMakeFiles/celine_tests.dir/src/tests/test_rank.cpp.o
.PHONY : src/tests/test_rank.cpp.o

src/tests/test_rank.i: src/tests/test_rank.cpp.i
.PHONY : src/tests/test_rank.i

# target to preprocess a source file
src/tests/test_rank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_tests.dir/build.make CMakeFiles/celine_tests.dir/src/tests/test_rank.cpp.i
.PHONY : src/tests/test_rank.cpp.i

src/tests/test_rank.s: src/tests/test_rank.cpp.s
.PHONY : src/tests/test_rank.s

# target to generate assembly for a file
src/tests/test_rank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/celine_tests.dir/build.make CMakeFiles/celine_tests.dir/src/tests/test_rank.cpp.s
.PHONY : src/tests/test_rank.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... celine_bin"
	@echo "... celine_lib"
	@echo "... celine_lib@synth_80f53022599d"
	@echo "... celine_tests"
	@echo "... src/celine/LinearApp.o"
	@echo "... src/celine/LinearApp.i"
	@echo "... src/celine/LinearApp.s"
	@echo "... src/celine/celine.o"
	@echo "... src/celine/celine.i"
	@echo "... src/celine/celine.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tests/test_rank.o"
	@echo "... src/tests/test_rank.i"
	@echo "... src/tests/test_rank.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

